# Generated by Django 6.0.1 on 2026-01-16 14:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HueyTaskAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("task_id", models.CharField(db_index=True, max_length=64)),
                (
                    "task_name",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("retries", models.IntegerField(blank=True, null=True)),
                ("eta", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("executing", "Executing"),
                            ("complete", "Complete"),
                            ("error", "Error"),
                            ("retrying", "Retrying"),
                            ("revoked", "Revoked"),
                            ("locked", "Locked"),
                            ("expired", "Expired"),
                            ("interrupted", "Interrupted"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("args_repr", models.TextField(blank=True)),
                ("kwargs_repr", models.TextField(blank=True)),
                ("exc_type", models.CharField(blank=True, max_length=255)),
                ("exc_message", models.TextField(blank=True)),
                ("traceback", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["task_name", "created_at"],
                        name="django_huey_task_na_5082a7_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="django_huey_status_d81e4e_idx",
                    ),
                ],
            },
        ),
    ]
