# Generated by Django 6.0.1 on 2026-08-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_huey_log", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hueytaskattempt",
            old_name="retries",
            new_name="retries_remaining",
        ),
        migrations.AlterField(
            model_name="hueytaskattempt",
            name="retries_remaining",
            field=models.IntegerField(
                blank=True,
                help_text="Huey's remaining-retry budget at the time of this attempt, i.e. task.retries as reported by huey -- NOT the number of attempts made so far. Decrements by one on each retry, so a task that succeeds on its first try always shows its originally configured `retries=` value (0 if unset).",
                null=True,
            ),
        ),
    ]
